---
name: String-MkPasswd
version: 0.03
author:
  - 'Chris Grau <cgrau@cpan.org>'
abstract: random password generator
license: perl
resources:
  license: http://dev.perl.org/licenses/
configure_requires:
  Module::Build: 0.35
provides:
  String::MkPasswd:
    file: lib/String/MkPasswd.pm
    version: 0.03
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
